---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: modelserver-nov28-2
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: modelserver-nov28-2 
  name: modelserver-nov28-2
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi