kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: modelserver-nov28-2-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: modelserver-nov28-2-dsp-job
    namespace: modelserver-nov28-2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modelserver-nov28-2-dsp-job-role